import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

       <div className="flex gap-4 p-4 bg-gray-800 text-xl font-bold">
          <Link href={`/`}>Logo</Link>
          <Link href={`/home`}>Home</Link>
          <Link href={`/blogs`}>blogs</Link>
     </div>
      <body className="min-h-full flex flex-col">{children}</body>
      <div className="flex bg-gray-800 justify-center items-center  bottom-0 fixed w-full p-5">
      <footer>
            <h2 className="font-bold text-2xl">Made with Next.js and Designed with TailwindCSS</h2> 
      </footer>
</div>
    </html>
  );
}


