import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

       <nav className="flex gap-4 p-4 bg-gray-800 text-xl font-bold">
          <Link href={`/`}>Logo</Link>
          <Link href={`/home`}>Home</Link>
          <Link href={`/blogs`}>blogs</Link>
     </nav>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}


